//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.24 at 09:06:12 AM JST 
//


package watson.dialog.tools.model.dao.xsd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for actionOperatorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="actionOperatorType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DO_NOTHING_STR"/>
 *     &lt;enumeration value="SET_TO"/>
 *     &lt;enumeration value="SET_TO_USER_INPUT"/>
 *     &lt;enumeration value="SET_TO_USER_INPUT_CORRECTED"/>
 *     &lt;enumeration value="INCREMENT_BY"/>
 *     &lt;enumeration value="DECREMENT_BY"/>
 *     &lt;enumeration value="SET_TO_YES"/>
 *     &lt;enumeration value="SET_TO_NO"/>
 *     &lt;enumeration value="YES"/>
 *     &lt;enumeration value="NO"/>
 *     &lt;enumeration value="SET_AS_USER_INPUT"/>
 *     &lt;enumeration value="SET_TO_BLANK"/>
 *     &lt;enumeration value="APPEND"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "actionOperatorType")
@XmlEnum
public enum ActionOperatorType {

    DO_NOTHING_STR,
    SET_TO,
    SET_TO_USER_INPUT,
    SET_TO_USER_INPUT_CORRECTED,
    INCREMENT_BY,
    DECREMENT_BY,
    SET_TO_YES,
    SET_TO_NO,
    YES,
    NO,
    SET_AS_USER_INPUT,
    SET_TO_BLANK,
    APPEND;

    public String value() {
        return name();
    }

    public static ActionOperatorType fromValue(String v) {
        return valueOf(v);
    }

}
