//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.24 at 09:06:12 AM JST 
//


package watson.dialog.tools.model.dao.xsd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for conditionOperatorType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="conditionOperatorType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EQUALS"/>
 *     &lt;enumeration value="CONTAINS"/>
 *     &lt;enumeration value="MATCHES_PATTERN"/>
 *     &lt;enumeration value="LESS_THEN"/>
 *     &lt;enumeration value="GREATER_THEN"/>
 *     &lt;enumeration value="EQUAL_TO_YES"/>
 *     &lt;enumeration value="EQUAL_TO_NO"/>
 *     &lt;enumeration value="IS_BLANK"/>
 *     &lt;enumeration value="HAS_VALUE"/>
 *     &lt;enumeration value="SET_TO"/>
 *     &lt;enumeration value="SET_TO_BLANK"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "conditionOperatorType")
@XmlEnum
public enum ConditionOperatorType {

    EQUALS,
    CONTAINS,
    MATCHES_PATTERN,
    LESS_THEN,
    GREATER_THEN,
    EQUAL_TO_YES,
    EQUAL_TO_NO,
    IS_BLANK,
    HAS_VALUE,
    SET_TO,
    SET_TO_BLANK;

    public String value() {
        return name();
    }

    public static ConditionOperatorType fromValue(String v) {
        return valueOf(v);
    }

}
