//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.04.24 at 09:06:12 AM JST 
//


package watson.dialog.tools.model.dao.xsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Dialog_QNAME = new QName("", "dialog");
    private final static QName _PromptTypeItem_QNAME = new QName("", "item");
    private final static QName _GrammarTypeSource_QNAME = new QName("", "source");
    private final static QName _GrammarTypeParam_QNAME = new QName("", "param");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FolderNodeType }
     * 
     */
    public FolderNodeType createFolderNodeType() {
        return new FolderNodeType();
    }

    /**
     * Create an instance of {@link GrammarType }
     * 
     */
    public GrammarType createGrammarType() {
        return new GrammarType();
    }

    /**
     * Create an instance of {@link RelatedNodesType }
     * 
     */
    public RelatedNodesType createRelatedNodesType() {
        return new RelatedNodesType();
    }

    /**
     * Create an instance of {@link DialogType }
     * 
     */
    public DialogType createDialogType() {
        return new DialogType();
    }

    /**
     * Create an instance of {@link IfNodeType }
     * 
     */
    public IfNodeType createIfNodeType() {
        return new IfNodeType();
    }

    /**
     * Create an instance of {@link ReportType }
     * 
     */
    public ReportType createReportType() {
        return new ReportType();
    }

    /**
     * Create an instance of {@link EntityValueType }
     * 
     */
    public EntityValueType createEntityValueType() {
        return new EntityValueType();
    }

    /**
     * Create an instance of {@link EntityType }
     * 
     */
    public EntityType createEntityType() {
        return new EntityType();
    }

    /**
     * Create an instance of {@link ProfileValueSubruleType }
     * 
     */
    public ProfileValueSubruleType createProfileValueSubruleType() {
        return new ProfileValueSubruleType();
    }

    /**
     * Create an instance of {@link HitNodeRuleType }
     * 
     */
    public HitNodeRuleType createHitNodeRuleType() {
        return new HitNodeRuleType();
    }

    /**
     * Create an instance of {@link SettingsType }
     * 
     */
    public SettingsType createSettingsType() {
        return new SettingsType();
    }

    /**
     * Create an instance of {@link EntitiesType }
     * 
     */
    public EntitiesType createEntitiesType() {
        return new EntitiesType();
    }

    /**
     * Create an instance of {@link GotoNodeType }
     * 
     */
    public GotoNodeType createGotoNodeType() {
        return new GotoNodeType();
    }

    /**
     * Create an instance of {@link ConstantsType }
     * 
     */
    public ConstantsType createConstantsType() {
        return new ConstantsType();
    }

    /**
     * Create an instance of {@link ActionType }
     * 
     */
    public ActionType createActionType() {
        return new ActionType();
    }

    /**
     * Create an instance of {@link ReportsType }
     * 
     */
    public ReportsType createReportsType() {
        return new ReportsType();
    }

    /**
     * Create an instance of {@link VarFolderType }
     * 
     */
    public VarFolderType createVarFolderType() {
        return new VarFolderType();
    }

    /**
     * Create an instance of {@link TranslationType }
     * 
     */
    public TranslationType createTranslationType() {
        return new TranslationType();
    }

    /**
     * Create an instance of {@link VariationsType }
     * 
     */
    public VariationsType createVariationsType() {
        return new VariationsType();
    }

    /**
     * Create an instance of {@link FlowType }
     * 
     */
    public FlowType createFlowType() {
        return new FlowType();
    }

    /**
     * Create an instance of {@link OutputNodeType }
     * 
     */
    public OutputNodeType createOutputNodeType() {
        return new OutputNodeType();
    }

    /**
     * Create an instance of {@link VarType }
     * 
     */
    public VarType createVarType() {
        return new VarType();
    }

    /**
     * Create an instance of {@link CondType }
     * 
     */
    public CondType createCondType() {
        return new CondType();
    }

    /**
     * Create an instance of {@link SettingType }
     * 
     */
    public SettingType createSettingType() {
        return new SettingType();
    }

    /**
     * Create an instance of {@link TranslationsType }
     * 
     */
    public TranslationsType createTranslationsType() {
        return new TranslationsType();
    }

    /**
     * Create an instance of {@link ConceptNodeType }
     * 
     */
    public ConceptNodeType createConceptNodeType() {
        return new ConceptNodeType();
    }

    /**
     * Create an instance of {@link InputNodeType }
     * 
     */
    public InputNodeType createInputNodeType() {
        return new InputNodeType();
    }

    /**
     * Create an instance of {@link SearchNodeType }
     * 
     */
    public SearchNodeType createSearchNodeType() {
        return new SearchNodeType();
    }

    /**
     * Create an instance of {@link ScriptType }
     * 
     */
    public ScriptType createScriptType() {
        return new ScriptType();
    }

    /**
     * Create an instance of {@link DefaultNodeType }
     * 
     */
    public DefaultNodeType createDefaultNodeType() {
        return new DefaultNodeType();
    }

    /**
     * Create an instance of {@link PromptType }
     * 
     */
    public PromptType createPromptType() {
        return new PromptType();
    }

    /**
     * Create an instance of {@link SpecialSettingsType }
     * 
     */
    public SpecialSettingsType createSpecialSettingsType() {
        return new SpecialSettingsType();
    }

    /**
     * Create an instance of {@link SpecialSettingType }
     * 
     */
    public SpecialSettingType createSpecialSettingType() {
        return new SpecialSettingType();
    }

    /**
     * Create an instance of {@link VariablesType }
     * 
     */
    public VariablesType createVariablesType() {
        return new VariablesType();
    }

    /**
     * Create an instance of {@link ProfileValueRulesType }
     * 
     */
    public ProfileValueRulesType createProfileValueRulesType() {
        return new ProfileValueRulesType();
    }

    /**
     * Create an instance of {@link RandomNodeType }
     * 
     */
    public RandomNodeType createRandomNodeType() {
        return new RandomNodeType();
    }

    /**
     * Create an instance of {@link GetUserInputNodeType }
     * 
     */
    public GetUserInputNodeType createGetUserInputNodeType() {
        return new GetUserInputNodeType();
    }

    /**
     * Create an instance of {@link HitNodeRulesType }
     * 
     */
    public HitNodeRulesType createHitNodeRulesType() {
        return new HitNodeRulesType();
    }

    /**
     * Create an instance of {@link FunctionNodeType }
     * 
     */
    public FunctionNodeType createFunctionNodeType() {
        return new FunctionNodeType();
    }

    /**
     * Create an instance of {@link ProfileValueRuleType }
     * 
     */
    public ProfileValueRuleType createProfileValueRuleType() {
        return new ProfileValueRuleType();
    }

    /**
     * Create an instance of {@link FolderNodeType.AutoLearnVariations }
     * 
     */
    public FolderNodeType.AutoLearnVariations createFolderNodeTypeAutoLearnVariations() {
        return new FolderNodeType.AutoLearnVariations();
    }

    /**
     * Create an instance of {@link GrammarType.Param }
     * 
     */
    public GrammarType.Param createGrammarTypeParam() {
        return new GrammarType.Param();
    }

    /**
     * Create an instance of {@link RelatedNodesType.RelNode }
     * 
     */
    public RelatedNodesType.RelNode createRelatedNodesTypeRelNode() {
        return new RelatedNodesType.RelNode();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DialogType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "dialog")
    public JAXBElement<DialogType> createDialog(DialogType value) {
        return new JAXBElement<DialogType>(_Dialog_QNAME, DialogType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "item", scope = PromptType.class)
    public JAXBElement<String> createPromptTypeItem(String value) {
        return new JAXBElement<String>(_PromptTypeItem_QNAME, String.class, PromptType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "source", scope = GrammarType.class)
    public JAXBElement<String> createGrammarTypeSource(String value) {
        return new JAXBElement<String>(_GrammarTypeSource_QNAME, String.class, GrammarType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GrammarType.Param }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "param", scope = GrammarType.class)
    public JAXBElement<GrammarType.Param> createGrammarTypeParam(GrammarType.Param value) {
        return new JAXBElement<GrammarType.Param>(_GrammarTypeParam_QNAME, GrammarType.Param.class, GrammarType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "item", scope = GrammarType.class)
    public JAXBElement<String> createGrammarTypeItem(String value) {
        return new JAXBElement<String>(_PromptTypeItem_QNAME, String.class, GrammarType.class, value);
    }

}
